/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// SheetResponsePayload contains the synchronized Google sheet
type SheetResponsePayload struct {
	Sheet string `json:"sheet,omitempty"`
}
