/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

type Zgroup struct {
	Archived bool `json:"archived,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Published bool `json:"published,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	ZoomLink string `json:"zoomLink,omitempty"`
}
