/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// ProfileResponsePayload contains user profile information
type ProfileResponsePayload struct {
	User *User `json:"user,omitempty"`
	Zgroup *Zgroup `json:"zgroup,omitempty"`
}
