/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type InlineResponse2003 struct {
	User *User `json:"user,omitempty"`
	Zgroup *Zgroup `json:"zgroup,omitempty"`
}
