/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// ErrorPayload wraps errors in a well-defined api payload
type ErrorPayload struct {
	Error_ string `json:"error,omitempty"`
}
