/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// AdminUsersResponsePayload contains the paginated users
type AdminUsersResponsePayload struct {
	Pagination *Pagination `json:"pagination,omitempty"`
	Users []UserWithZgroup `json:"users,omitempty"`
}
