/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type InlineResponse2002 struct {
	Users []User `json:"users,omitempty"`
	Zgroup *Zgroup `json:"zgroup,omitempty"`
}
