/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// AdminUserResponsePayload contains the queried user
type AdminUserResponsePayload struct {
	User *UserWithZgroup `json:"user,omitempty"`
}
