/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type InlineResponse200 struct {
	Pagination *Pagination `json:"pagination,omitempty"`
	Users []User `json:"users,omitempty"`
}
