/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// GroupResponsePayload contains the queried group and its users
type GroupResponsePayload struct {
	Group *Group `json:"group,omitempty"`
	Users []User `json:"users,omitempty"`
}
