/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

type User struct {
	Blocked bool `json:"blocked,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	Email string `json:"email,omitempty"`
	Id int64 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
