/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// GroupsResponsePayload contains paginated groups
type GroupsResponsePayload struct {
	Groups []Group `json:"groups,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}
