/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// UsersResponsePayload contains the paginated users
type UsersResponsePayload struct {
	Pagination *Pagination `json:"pagination,omitempty"`
	Users []UserWithGroup `json:"users,omitempty"`
}
