/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Pagination holds query data for pagination
type Pagination struct {
	Cursor int64 `json:"cursor,omitempty"`
	Limit int64 `json:"limit,omitempty"`
}
