/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// TokenPayload contain the body parameters for a token exchange
type TokenPayload struct {
	Token string `json:"token,omitempty"`
}
