/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// AdminZgroupsResponsePayload contains paginated zgroups
type AdminZgroupsResponsePayload struct {
	Pagination *Pagination `json:"pagination,omitempty"`
	Zgroups []Zgroup `json:"zgroups,omitempty"`
}
