/*
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// UserResponsePayload contains the queried user
type UserResponsePayload struct {
	User *UserWithGroup `json:"user,omitempty"`
}
