// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testAdminSessions(t *testing.T) {
	t.Parallel()

	query := AdminSessions()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testAdminSessionsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AdminSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAdminSessionsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := AdminSessions().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AdminSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAdminSessionsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AdminSessionSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := AdminSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testAdminSessionsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := AdminSessionExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if AdminSession exists: %s", err)
	}
	if !e {
		t.Errorf("Expected AdminSessionExists to return true, but got false.")
	}
}

func testAdminSessionsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	adminSessionFound, err := FindAdminSession(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if adminSessionFound == nil {
		t.Error("want a record, got nil")
	}
}

func testAdminSessionsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = AdminSessions().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testAdminSessionsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := AdminSessions().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testAdminSessionsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	adminSessionOne := &AdminSession{}
	adminSessionTwo := &AdminSession{}
	if err = randomize.Struct(seed, adminSessionOne, adminSessionDBTypes, false, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}
	if err = randomize.Struct(seed, adminSessionTwo, adminSessionDBTypes, false, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = adminSessionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = adminSessionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AdminSessions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testAdminSessionsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	adminSessionOne := &AdminSession{}
	adminSessionTwo := &AdminSession{}
	if err = randomize.Struct(seed, adminSessionOne, adminSessionDBTypes, false, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}
	if err = randomize.Struct(seed, adminSessionTwo, adminSessionDBTypes, false, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = adminSessionOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = adminSessionTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdminSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testAdminSessionsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdminSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAdminSessionsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(adminSessionColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := AdminSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testAdminSessionsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAdminSessionsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := AdminSessionSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testAdminSessionsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := AdminSessions().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	adminSessionDBTypes = map[string]string{`ID`: `integer`, `IP`: `character varying`, `Email`: `character varying`, `CreatedAt`: `timestamp with time zone`}
	_                   = bytes.MinRead
)

func testAdminSessionsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(adminSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(adminSessionAllColumns) == len(adminSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdminSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testAdminSessionsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(adminSessionAllColumns) == len(adminSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &AdminSession{}
	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := AdminSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, adminSessionDBTypes, true, adminSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(adminSessionAllColumns, adminSessionPrimaryKeyColumns) {
		fields = adminSessionAllColumns
	} else {
		fields = strmangle.SetComplement(
			adminSessionAllColumns,
			adminSessionPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := AdminSessionSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testAdminSessionsUpsert(t *testing.T) {
	t.Parallel()

	if len(adminSessionAllColumns) == len(adminSessionPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := AdminSession{}
	if err = randomize.Struct(seed, &o, adminSessionDBTypes, true); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AdminSession: %s", err)
	}

	count, err := AdminSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, adminSessionDBTypes, false, adminSessionPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize AdminSession struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert AdminSession: %s", err)
	}

	count, err = AdminSessions().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
