// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AdminSessions string
	OauthUsers    string
	Oauths        string
	Sessions      string
	Users         string
	ZgroupMembers string
	Zgroups       string
}{
	AdminSessions: "admin_sessions",
	OauthUsers:    "oauth_users",
	Oauths:        "oauths",
	Sessions:      "sessions",
	Users:         "users",
	ZgroupMembers: "zgroup_members",
	Zgroups:       "zgroups",
}
