// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	OauthUsers    string
	Oauths        string
	Users         string
	ZgroupMembers string
	Zgroups       string
}{
	OauthUsers:    "oauth_users",
	Oauths:        "oauths",
	Users:         "users",
	ZgroupMembers: "zgroup_members",
	Zgroups:       "zgroups",
}
