// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AdminSessions string
	GroupMembers  string
	Groups        string
	OauthUsers    string
	Oauths        string
	Sessions      string
	Settings      string
	Users         string
}{
	AdminSessions: "admin_sessions",
	GroupMembers:  "group_members",
	Groups:        "groups",
	OauthUsers:    "oauth_users",
	Oauths:        "oauths",
	Sessions:      "sessions",
	Settings:      "settings",
	Users:         "users",
}
